frontend/android/src/main/res/layout/main.xml
=> Select all search text on focus.

frontend/android/src/main/java/com/jakewharton/sdksearch/ui/ItemAdapter.kt, frontend/android/src/main/java/com/jakewharton/sdksearch/ui/MainActivity.kt, frontend/android/src/main/res/layout/main.xml
=> Launch first result on IME action or enter key.

frontend/android/src/main/res/layout/main.xml
=> Enable scrollbars in results list.

frontend/android/src/main/java/com/jakewharton/sdksearch/ui/OpenDocumentationItemHandler.kt, frontend/android/src/main/java/com/jakewharton/sdksearch/util/DrawableExtensions.kt, frontend/android/src/main/res/drawable/ic_code_black_24dp.xml
=> Show 'view source' as action button

frontend/android/src/main/java/com/jakewharton/sdksearch/ui/ItemViewHolder.kt
Example from pressing the 3rd item.
=> Make the popup menu overlap the button

frontend/android/src/main/java/com/jakewharton/sdksearch/ui/MainActivity.kt, frontend/android/src/main/res/drawable/list_divider.xml
=> Use more subtle list divider

frontend/android/src/main/java/com/jakewharton/sdksearch/ui/ItemViewHolder.kt, frontend/android/src/main/java/com/jakewharton/sdksearch/ui/LetterSpacingSpan.kt
Reduce letter spacing and text alpha on periods.
=> More text styling text for items

frontend/android/src/main/java/com/jakewharton/sdksearch/ui/MainActivity.kt
Closes #32. Can't check in the run config because of https://issuetracker.google.com/issues/65046888.
=> Allow injecting a default query from intent extras.

frontend/android/build.gradle, frontend/android/src/main/java/com/jakewharton/sdksearch/SdkSearchApplication.kt
=> Remove dependency on java.time.*.

build.gradle, db/build.gradle, db/src/androidTest/java/com/jakewharton/sdksearch/db/ItemStoreTest.kt, db/src/main/java/com/jakewharton/sdksearch/db/SqlItemStore.kt, db/src/main/sqldelight/com/jakewharton/sdksearch/db/Item.sq
=> Escape LIKE wildcard characters.

frontend/chrome-extension/src/main/kotlin/com/jakewharton/sdksearch/Main.kt, store/js/src/main/kotlin/com/jakewharton/sdksearch/store/StorageAreaItemStore.kt
=> Sort JS results the same as Android and render to Omnibox.

frontend/android/src/main/java/com/jakewharton/sdksearch/ui/MainActivity.kt, frontend/android/src/main/res/values-v26/styles.xml, frontend/android/src/main/res/values-v27/styles.xml, frontend/android/src/main/res/values/styles.xml
=> Use a white nav bar on API 26+.

search/ui/src/main/java/com/jakewharton/sdksearch/search/ui/ItemViewHolder.kt
This was added here https://github.com/android/android-ktx/pull/388 and released in `0.3`
=> Use spannable.set from core-ktx

.circleci/config.yml, frontend/chrome-extension/background/build.gradle, frontend/chrome-extension/content/build.gradle, frontend/chrome-extension/options/build.gradle, frontend/web/build.gradle
Require it be installed on the system.
=> Do not download node

.circleci/config.yml, .circleci/images/primary/Dockerfile, .gitignore, build.gradle, frontend/chrome-extension/content/src/main/kotlin/com/jakewharton/sdksearch/content/Content.kt, references/js/build.gradle, references/js/src/main/kotlin/com/jakewharton/sdksearch/reference/Extensions.kt, references/js/src/test/kotlin/com/jakewharton/sdksearch/reference/ExtensionsTest.kt, references/src/main/kotlin/com/jakewharton/sdksearch/reference/AndroidReference.kt, references/src/test/kotlin/com/jakewharton/sdksearch/reference/AndroidReferenceTest.kt
=> Strip non-path components from source URL lookups

build.gradle, debug-updater/build.gradle, debug-updater/src/main/AndroidManifest.xml, debug-updater/src/main/java/com/jakewharton/sdksearch/debug/updater/UpdateActivity.kt, debug-updater/src/main/java/com/jakewharton/sdksearch/debug/updater/UpdateService.kt, frontend/android/build.gradle, gradle.properties, options/ui-android/build.gradle, options/ui-android/src/main/java/com/jakewharton/sdksearch/options/ui/OptionsUiBinder.kt, options/ui-android/src/main/res/layout/options.xml, roboto/build.gradle, search/ui-android/build.gradle, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/ClipboardCopyItemHandler.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/ItemAdapter.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/ItemDiffer.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/ItemViewHolder.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/OpenDocumentationItemHandler.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/OpenSourceItemHandler.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/SearchUiBinder.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/ShareItemHandler.kt, search/ui-android/src/main/java/com/jakewharton/sdksearch/search/ui/util/RecyclerViewExtensions.kt, search/ui-android/src/main/res/layout/item.xml, search/ui-android/src/main/res/layout/search.xml, store/config/android-preferences/build.gradle, store/item/android-sql/build.gradle, store/item/android-sql/src/androidTest/java/com/jakewharton/sdksearch/store/ItemStoreTest.kt
We're forced to downgrade Dagger because of a Jetifier bug.
=> Migrate to AndroidX

dagger-reflect/reflect/src/main/java/dagger/reflect/ReflectiveMembersInjector.java, dagger-reflect/reflect/src/test/java/dagger/DaggerTest.java, dagger-reflect/reflect/src/test/java/dagger/reflect/ReflectiveMembersInjectorTest.java
=> Error messages for @Inject private/static members

dagger-reflect/reflect/src/main/java/dagger/reflect/ReflectiveMembersInjector.java, dagger-reflect/reflect/src/test/java/dagger/reflect/ReflectiveMembersInjectorTest.java
=> Methods with @Inject may not be abstract

.circleci/config.yml
This rebases on the upstream CircleCI image which now includes the latest build-tools.
=> Docker image 0.0.3

api/dac/jdk-temp/build.gradle
I was getting this error at runtime startup.
java.lang.NoClassDefFoundError: Failed Resolution of: lkotlinx/serialization/json/JSON;
=> Add kotlin serialization library to fix NoClassDefFoundError at runtime.
